### ISSUE TITLE
Darcs repository - dates

### ISSUE THREAD

**Issue by phoe** [pcostanza/closer-mop#11]
I see that Closer to MOP was converted from a darcs repository, https://github.com/pcostanza/closer-mop/commit/4692dc1b392494dd439618e08657ecbbc8f39411

Do you perhaps have that repository anywhere? I am looking for its commit history and the date of the first commit.

**Comment by pcostanza** [comment]
Yes, I have it on my private computer. Where do you want me to put it? I could send you a zip by email...

**Comment by phoe** [comment]
Sure thing - `phoe` at `disroot.org`.

**Comment by pcostanza** [comment]
Ok, I have just sent it to you.
