### ISSUE TITLE
Bad conditionalization for lispworks with-hash-table-locked

### ISSUE THREAD

**Issue by Yehouda** [pcostanza/closer-mop#13]
In closer-mop-packages.lisp, the conditionalization for LispWorks of with-hash-table-locked is
  #+(or lispworks6 lispworks7), which means it will not work in LispWorks 8. It should
be #-(or lispworks4 lispworks5).

**Comment by pcostanza** [comment]
As far as I can tell, there is no LispWorks 8, so I cannot test whether closer-mop will actually work on LispWorks 8. I prefer to conditionalize only for implementations where closer-mop actually works.

**Comment by Yehouda** [comment]
That means we (LispWorks Ltd) cannot run our automatic tests on it or any Quicklisp system that uses it and uses eql-specializer (because that is where it breaks).

**Comment by pcostanza** [comment]
Ok, that's indeed a serious issue. I will fix this ASAP, as you suggested in your original report. Thanks a lot for brining this up.

**Comment by Yehouda** [comment]
Thanks.

**Comment by pcostanza** [comment]
I have just committed the fix to this repository. It should normally become part of the next Quicklisp update (but that's not under my control).

Thanks again for reporting this issue.

**Comment by quicklisp** [comment]
This change breaks closer-mop on all non-LispWorks lisps.

**Comment by Yehouda** [comment]
Yes, it should really be 

   #+(and lispworks (not (or lispworks4 lispworks5)))

Even simpler is to remove the import and to conditionalize just the
place it is used in closer-lispworks.lisp 

   (#+lispworks5.1 sys:with-hash-table-locked
    #-lispworks5.1 hcl:with-hash-table-locked

**Comment by pcostanza** [comment]
Zach: Thanks a lot for paying attention. Indeed this was a mistake. I now fixed it, same as Yehouda's first suggestion for the import clause. I hope this is fine now and I haven't overlooked anything else.
