### ISSUE TITLE
irregurality on ABCL

### ISSUE THREAD

**Issue by guicho271828** [pcostanza/closer-mop#3]
on ABCL, `class-slots` to a `structure-class` returns objects of `system::defstruct-slot-description` , not `slot-definition`.

**Comment by pcostanza** [comment]
Per MOP specification, `class-slots` is not specified for `structure-class`, so any behavior on a `structure-class` is implementation-specific and non-portable.

**Comment by guicho271828** [comment]
oh, I didnt notice that. thanks!
